[package]
name = "vm-translator"
version = "0.1.0"
authors = ["Hamish Miller <hamishcomiller@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
